Unity-Technologies/com.unity.formats.fbx

com.unity.formats.fbx/Editor/FbxExporter.cs

only use root skeleton type if root bone has child bones

UT-3243 fix mesh separating from bones in Maya

---

.yamato/promotion.yml
.yamato/upm-ci.yml

Also remove a job we weren't using, and make a virtual job from a job that was
doing nothing on its machine (fixing a warning, speeding up builds).
This is stuff I saw while working on the soft dependence.

Update to 2019.3

---

com.unity.formats.fbx/Editor/FbxExporter.cs

If the name of a FbxShape backing a blendshape channel is left as an empty string, multiple blend shapes on the same object fail to export properly. Only the last blendshape modifier is used, regardless of which is enabled. This fixes it.

Fix FBX shape naming for blendshapes

---

com.unity.formats.fbx/Editor/Sources/Recorders/FbxRecorder/FbxRecorder.cs

- baking, reducing keyframes and baking again can create unnecessary errors/discrepancies in the exported curve.
- for the particular issue being fixed (UT-3313), the recorded curves originally had constant/linear tangents, which then became cubic after recording (as the recorder loses tangent information). This combined with keyframe reduction resulted in jitteryness where there should have been clean transitions between blocking positions.

UT-3313 don't reduce keyframes after recording and before exporting

---

com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs

NOTE: yamato tests won't pass yet as there are still other unit tests failing

fix continous rotation test failing for equivalent rotations

---

com.unity.formats.fbx/Editor/FbxExporter.cs

- also force unique names for materials and textures
This fixes fogbug: https://fogbugz.unity3d.com/f/cases/1193945/

UT-3382 map by ID instead of name for materials and meshes

---

com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs
com.unity.formats.fbx/Tests/Models/blendshape.fbx.meta
com.unity.formats.fbx/Tests/Models/blendshape_with_skinning.fbx.meta
com.unity.formats.fbx/package.json

make sure blendshape normals aren't imported on the original FBX files
If blendshape normals are imported the vertex count between the original and exported meshes won't match. They can't be imported for either the exported file or the original one.

UT-3401 fix failing blendshape unit tests

---

Integrations/Autodesk/maya/scripts/unityCommands.mel

If strip namespaces checked, automatically find most common namespace to strip on export. Unless the user enters a custom namespace in the text field, then strip that instead.

Ut 3411 add checkbox to strip all namespaces

---

com.unity.formats.fbx/Editor/FbxExporter.cs

When exporting bones of skinned meshes, their transform values are first set to the bindpose, so that the skin and bindpose are exported properly.
However, afterwards we need to set the bones back to their original transform values so that if the character is not in the bindpose on export, the same pose is maintained in the FBX.
This fixes fogbug: https://fogbugz.unity3d.com/f/cases/1185725/

UT-3389 export bones in original position instead of bindpose

---

Integrations/Autodesk/maya/scripts/unityCommands.mel

The option is broken and ultimately not necessary as you won't have the issue of name clashes like when importing an FBX

UT-3430 remove namespace option from create export set dialogs

---

com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs

- pass optional import settings to ExportSkinnedMesh
- change import settings for both original and exported mesh to make sure they match

UT-3390 fix failing unit tests on 2018.3

---

CHANGELOG.md
Integrations/Autodesk/max/scripts/UnityFbxForMaxPlugin.ms

Previously, when no objects are selected, exporting to Unity creates an empty FBX file:
In 3ds Max, export should only be possible if an object or export set is selected.
Selecting "Export to Unity" or "Export to Unity (Model Only)" with no selection now does nothing. This is to match the current behavior in Maya.
Updating ChangeLog.

UT-3484: When no objects are selected, exporting to Unity creates an empty FBX file

---

com.unity.formats.fbx/Editor/FbxExporter.cs

Temp fbx file is now created in the directory where the exported fbx file will be created so that the relative path to textures is correct.

UT-3125 Relative path of texture fix

---

com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs
com.unity.formats.fbx/Editor/ExportModelSettings.cs
com.unity.formats.fbx/Editor/FbxExportSettings.cs
com.unity.formats.fbx/Tests/FbxApiTests/PublicAPITest.cs
com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs
com.unity.formats.fbx/Tests/Scripts/ExporterTestBaseAPI.cs

Can now export fbx models outside of the Assets folder in the Unity project.
Cannot export fbx models outside the project if converting to a prefab.
Preserve import settings checkbox greyed out if you're exporting outside the project.

UT-3305 Export Outside Assets Folder

---

com.unity.formats.fbx/Editor/FbxExporter.cs
com.unity.formats.fbx/Tests/FbxApiTests/PublicAPITest.cs
com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs

When exporting a hierarchy of game objects, any objects with duplicate meshes now export as instances.

UT-3419 Duplicate meshes export as instances.

---

com.unity.formats.fbx/Editor/FbxExporter.cs

Add null checks whenever accessing a bone, so that export doesn't fail with a broken rig.

Add null checks when accessing bones.

---

com.unity.formats.fbx/Editor/ExportModelSettings.cs

Label Preserve Import Settings checkbox was getting cut off in a bad spot on Mac.

Fix label getting cut off.

---

com.unity.formats.fbx/Editor/CameraVisitor.cs
com.unity.formats.fbx/Tests/FbxTests/FbxCameraTests.cs

- `Handles.GetMainGameViewSize();` (public API) now used
- Modifying unit test to check for aspect ratio (set using the value returned by `GetSizeOfMainView()`)

FBX-31 CameraVisitor.cs no longer using Reflection

---

QAReport.md

I noticed that this hasn't been updated for 4.0.0.

[skip ci] Update QAReport.md for 4.0.0

---

com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs

test failing because of a new import option that is now disabled by default but was previously always enabled (with no option to disable)

FBX-87 fix test failing on 2021.2

---

CHANGELOG.md
com.unity.formats.fbx/Documentation~/exporting.md
com.unity.formats.fbx/Editor/FbxExporter.cs
com.unity.formats.fbx/Editor/FbxPropertyChannelPair.cs
com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs

Adding support to export animations of blendshapes created in either Maya or Unity.
Requires the Animate Skinned Mesh export option to be selected.

FBX-37: Export Blendshape Animations

---

CHANGELOG.md
com.unity.formats.fbx/Documentation~/recorder.md
com.unity.formats.fbx/Editor/Sources/Recorders/FbxRecorder/FbxRecorderSettings.cs
com.unity.formats.fbx/Editor/Unity.Formats.Fbx.Editor.asmdef
com.unity.formats.fbx/Tests/FbxTests/FbxRecorderTest.cs
com.unity.formats.fbx/Tests/FbxTests/FbxRecorderTest.cs.meta
com.unity.formats.fbx/Tests/Unity.Formats.Fbx.Editor.Tests.asmdef

* Adding public API call to ifdef
* Adding automated test file (TODO: currently only testing get/set binding functionality but eventually the entire Recorder workflow should be tested)
* Modifying the test assembly definition file to reference the Unity.Recorder assembly and set the `#if ENABLE_FBX_RECORDER` pre-processor definition

FBX-30: FbxRecorderSettings uses reflection but doesn't need to

---

com.unity.formats.fbx/Editor/ConvertToNestedPrefab.cs

These methods (in trunk) will become public soon. Change the bindingFlags for InvokeMethod to search for both public and non-public methods so the method won't fail. This is temporary until the API change lands, after which we can remove reflection for Unity > 2021.2.?.
Tested locally against `branch editor/public-api-for-getting-and-setting-icons`

FBX-76: fix invocation of Get/SetIconForObject when methods are public

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs

Fix null reference exception when materials are missing.
Default material is assigned if material is null.
Resulting fbx of gameobject will missing materials:

Add null material check

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs

Fix ArrayOutOfBoundsException when trying to export a gameobject with no name.
Added to changelog and combined both unreleased sections into one.

FBX-97 Fix error when exporting object with empty name

---

CHANGELOG.md
com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs

Fix the misaligned text in export file name field.

FBX-139 Fix misaligned text

---

CHANGELOG.md
com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs

Adjust SelectableLabelMinWidth to fit the names of game obejcts better.
Add ExportButtonWidth to window width so the export button is no longer cut off.

FBX-63 Fix window width

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs

Fix metafile warning when exporting an fbx.
Fix absolute path warning when overwriting an fbx.

FBX-6 Fix metafile warning

---

CHANGELOG.md
com.unity.formats.fbx/Editor/ConvertToPrefabEditorWindow.cs
com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs
com.unity.formats.fbx/Editor/FbxExportSettings.cs

Change file selector so that the option to create a new folder is added.
Changed file selector window for fbx export, prefab export, and fbx export project settings.

FBX 67 Fix new folder button on Mac

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExportSettings.cs
com.unity.formats.fbx/Tests/FbxTests/FbxExportSettingsTest.cs

Add reset functionality for FBX export project settings menu.
Add `Reset()` to `FbxExportSettings`.
Fix `dccOptionNames` being reset to null instead of empty list.

FBX-142 Fix reset settings

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs

Fix hdrp materials being exported with maximum incandescence/emission in Maya and Unity.

FBX-2 Fix hdrp incandescence

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs
com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs

Fix error when exporting a game object with a missing mesh.
Reformat `ExportInstance` code and simplify instance export.

FBX-1 Fix null shared mesh

---

CHANGELOG.md
com.unity.formats.fbx/package.json

errors are due to updating the com.autodesk.fbx version (not yet published)

FBX-168 update version and changelog

---

com.unity.formats.fbx/Editor/ExportModelSettings.cs
com.unity.formats.fbx/Editor/FbxExporter.cs

This PR includes two new export options:
1. **Embed Textures:** fixes a number of issues with the FBX exporter and interoperability, since relative/absolute texture paths don't matter anymore for external software. The resulting file is a monolithic FBX that contains all textures as embedded resources (very useful for interop). (Fixes Case 1201937)
2. **Keep Instances:** fixes issues with for example Blender and multimaterials on instances. Currently, when making a scene with 4 default Unity cubes with separate materials and exporting that to blender, the import result will be broken since a number of softwares don't properly support instances with individual materials. While this is clearly a bug somewhere else, this option allows to export all meshes as individual, unique ones and thus …

Feature: New export options to embed textures and export unique meshes

---

CHANGELOG.md
com.unity.formats.fbx/package.json

Note: this will fail validation steps until the FBX SDK package is on candidates.

FBX-317 (Release 4.2.0) update package version and changelog

---

com.unity.formats.fbx/Documentation~/troubleshooting.md
com.unity.formats.fbx/Editor/ConvertToNestedPrefab.cs
com.unity.formats.fbx/Editor/FbxExporter.cs
com.unity.formats.fbx/Runtime/FbxPrefab.cs

[FBX-328](https://jira.unity3d.com/browse/FBX-328) - Documentation wrap-up before FBX Exporter 4.2.0 release
- API doc xml formatting issue fixes
- Bad link correction
- Small text formatting fix

FBX-328 - Doc tag/link/formatting fixes

---

.yamato/upm-ci.yml

**Purpose of this PR:**
In order to fix CI failures because of upm-ci update to 1.28.0, specifically this change: `Deprecated downloading unity-downloader-cli on the fly and making it a hard dependency. `
Image `ubuntu:prev-stable` has no `unity-downloader-cli` pre-installed, but `ubuntu:stable` has.
By updating Ubuntu image to `ubuntu:stable`, it will resolve the "unity-downloader-cli" not being installed issue, unless there are specific reasons that we have to stick with `ubuntu:prev-stable`.
[FBX-333](https://jira.unity3d.com/browse/FBX-333): CI jobs fail for FBX on Linux platform because of upm-ci update.

Fix CI failures on Ubuntu by using ubuntu:stable image

---

com.unity.formats.fbx/Editor/FbxExporter.cs

New PR to fix issues with following PR: https://github.com/Unity-Technologies/com.unity.formats.fbx/pull/652
Contents:
Use count and length properties instead of LINQ call.
Array/List can not be under 0, so array size will be checked as == 0 instead of <= 0.
Use TryGetComponent to reduce memory allocation when no component is found.
GetComponent Mesh will always return null. Get MeshFilter.mesh instead.
Simplify string comparison using IndexOf, which does not create garbage.
Cache animation controller layers to avoid an extra internal call

FbxExporter.cs Improvements

---

com.unity.formats.fbx/Editor/Sources/Recorders/FbxRecorder/FbxRecorder.cs
com.unity.formats.fbx/Editor/Sources/Recorders/FbxRecorder/FbxRecorderSettings.cs

Fix an error when recording from a recorder track (end recording is called twice, need to check if the recording has already ended to not try to export twice).
Also fix the animation compression setting not being used.

Nojira/fix fbxrecorder with 4.0.0 recorder

---

.yamato/upm-ci.yml

This is to add API docs validation test to FBX's CI.
**JIRA Ticket:**
[FBX-338](https://jira.unity3d.com/browse/FBX-338) CI: Add Package Validation Profiles (PVP)'s API docs validation test to FBX package

JIRA FBX-338: Add API docs validation to CI

---

com.unity.formats.fbx/Editor/FbxExporter.cs

Seeing some cases where vertexCount != vertices.Length

Use array length instead of vertexCount

---

.yamato/upm-ci.yml

4.2 is no longer the latest version and it is taking the newer 5.0.0-pre.1 com.autodesk.fbx package instead of 4.2.1.

Remove trunk from nightly testing for 4.2

---

com.unity.formats.fbx/Editor/FbxPropertyChannelPair.cs

if the other attempts to get the property would fail it would try to regex regular properties like LocalPosition with this function.

FBX-377 make sure GetFbxBlendshapeProperty only happens for blendshapes

---

com.unity.formats.fbx/Editor/CameraVisitor.cs
com.unity.formats.fbx/Tests/FbxTests/FbxCameraTests.cs

This reverts commit 3ea2afb4801338ea3a5dff78b4047b763aed6a7f.
Reverting this change as it breaks the automated tests as this change is partially on com.autodesk.fbx repo, which would need to be republished for the tests here to find it.

Revert "FBX 382 export focus distance"

---

.yamato/global.metafile
.yamato/upm-ci.yml
build.sh

Enable APV clean console test in FBX packages
**JIRA tickets:**
[FBX-451](https://jira.unity3d.com/browse/FBX-451): Enable APV clean console test in FBX packages
**List of changes:**
- Enable APV clean console test for package test
- Update deprecated bokken images with new ones
- Install cmake on new Ubuntu18.04 image, new image doesn't have cmake preinstalled
- Add `set -e` to build.sh so that the build script will fail immediately if any build command fails. Otherwise build.sh just fails silently and pack job will give false positive, then all CI jobs fail. This problem has bited people several times.
**Notes to reviewers:**
You can see there are instabilities in trunk tests on Mac and Win, that's because of `'Object.FindObjectsOfType<T>()' is obsolete: 'Object.FindObjectsOfType has …

FBX-451 Enable APV clean console test in FBX packages

---

.yamato/clean-console-test.yml
.yamato/global.metafile
.yamato/upm-ci.yml
com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs
com.unity.formats.fbx/Editor/FbxExportPresetSelectorReceiver.cs

Add clean console tests to FBX packages.
In PR trigger, clean console tests only run on Windows.
In nightly trigger, clean console tests run on all platforms.
In this PR, I also temporarily disabled the obsolete warnings about class `PresetSelectorReceiver` and `PresetSelector.ShowSelector` which are tracked as FBX452.
[FBX-477](https://jira.unity3d.com/browse/FBX-477) Add clean console test to FBX packages

FBX-477 Add clean console test to FBX packages

---

.yamato/global.metafile

`Build on Mac` job fails for `com.autodesk.fbx` package because of macos-12 image update from `v4.19.0` to `v.4.20.0`.
Because `com.unity.formats.fbx` package runs CI using `com.autodesk.fbx` repo, so a fix is also needed here.
[FBX-479](https://jira.unity3d.com/browse/FBX-479) CI: Fix build job failures on Mac

FBX-479: Pin mac image to v4.19.0 so that build job can pass on Mac

---

.yamato/global.metafile
.yamato/upm-ci.yml
com.unity.formats.fbx/Tests/FbxTests/FbxExportSettingsTest.cs
com.unity.formats.fbx/Tests/Prefabs/Unity.Formats.Fbx.Editor.Tests.Prefabs.asmdef
com.unity.formats.fbx/Tests/Unity.Formats.Fbx.Editor.Tests.asmdef

The goal is to make the tests run again on our CI again. 
Issues remain on Ubuntu18 (so with APV/QV), but can be workaround using the package exemption mechanism. 
- Re-enabling Linux tests
- Updating to Ubuntu20 to avoid the libstdc++ error that happens on Ubuntu18.
- Disable Maya / Max integrations tests as we don't support the integrations in Linux
- A follow-up task has been logged to exempt the tests in unity/unity UnityPackageManager.cs (cf [FBX-101](https://jira.unity3d.com/browse/FBX-101))

Re-enable Ubuntu tests (FBX-468)

---

.yamato/global.metafile
.yamato/upm-ci.yml

- Add a `publish dry-run` job 
- Change test_trigger to a PR trigger which only runs when a PR is created. Currently it runs with every push in any branch which is annoying
- Add 2022.3 and 2023.2 to CI
[FBX-369](https://jira.unity3d.com/browse/FBX-369) CI: Change FBX's test_trigger to a PR trigger and add publish dryrun job
**Note:** This PR is mainly for adding publish dry run job (for the release) together with some minor changes and cleanup.
A refactoring of the CI is needed and will be done in a separate task.

FBX-369 CI: Change FBX's test_trigger to a PR trigger and add publish dryrun job

---

.yamato/clean-console-test.yml
.yamato/global.metafile
.yamato/package-test-utr.yml
.yamato/upm-ci.yml

-  Add Silicon Mac to FBX exporter's CI.
- Only run tests in 2023.2 and trunk on Silicon Mac because of known issues in older Editor versions caused by .NET.
- In this PR, I also removed some unless codes related to download UTR because `UnifiedTestRunner` is pre-installed on package-ci bokken images now.
[FBX-132](https://jira.unity3d.com/browse/FBX-132) Run automated tests on Apple Silicon machine

CI: FBX-132 Add silicon Mac to FBX exporter CI

---

.yamato/upm-ci.yml

Add doc generation job to FBX Exporter package and add a PR trigger for doc only changes.
[FBX-496](https://jira.unity3d.com/browse/FBX-496) CI: Add documentation generation job for FBX CI and a corresponding doc change trigger.

CI: Add documentation generation job for FBX CI and a corresponding doc change trigger.

---

.yamato/upm-ci.yml

Update deprecated bokken images for release 4.1 branch. 
Currently release/4.1 branch is still using old bokken images such as `upm-ci/win10:stable`. Because of that we can see following errors in CI:
```
Please switch to 'package-ci/win10:v4' or another supported Bokken image (note that package-ci/*:stable is deprecated and should no longer be used).
```
Besides, I also see CI failures caused by UPM-CI because of the following error:
```
Could not use "nc", falling back to slower node.js method for sync requests.
```
Updating deprecated bokken images seems to solve the issues above.
[FBX-497](https://jira.unity3d.com/browse/FBX-497) CI: Update bokken images for release/4.1

CI: Update bokken images for release 4.1 branch

---

.yamato/upm-ci.yml

Update deprecated bokken images for release 4.2 branch.
[FBX-497](https://jira.unity3d.com/browse/FBX-497) CI: Update bokken images for release/4.2

CI: Update bokken images for release 4.2 branch

---

.yamato/global.metafile
.yamato/package-test-utr.yml
.yamato/upm-ci.yml
build.cmd

Add test jobs on ARM64 Win. 
I also did some cleanup to the CI.
[FBX-519](https://jira.unity3d.com/browse/FBX-519) CI: Add package test jobs for ARM64 Windows

CI: Add test jobs on ARM64 Win

---

.yamato/clean-console-test.yml

This is a complementary PR to #716 in which I forgot to make sure clean console test only run in trunk if on ARM64 Windows.
[FBX-519](https://jira.unity3d.com/browse/FBX-519) CI: Add package test jobs for ARM64 Windows

CI: Only run clean console test in trunk if on ARM64 Win

---

.yamato/global.metafile

`com.unity.formats.fbx@5.0.0` only supports up to Editor `2023.1`.
Remove trunk and do some cleanup for CI of release/5.0 branch, such as:
- Update editor 2022.1 to 2022.3
- Remove some useless codes in yml file

CI: Remove trunk and do some cleanup for CI of release/5.0 branch

---

com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs

Disable test AnimOnlyExportTest because of an issue in FBX Export SDK. For the details of the issue, see [FBX-525](https://jira.unity3d.com/browse/FBX-525).
[FBX-530](https://jira.unity3d.com/browse/FBX-530) CI: Disable test FbxAnimationTest.AnimOnlyExportTest

CI: Disable test AnimOnlyExportTest because of an issue in FBX SDK

---

.yamato/pack-autodesk-fbx.yml

ARM64 Win build job has been added to `com.autodesk.fbx` package through [PR](https://github.com/Unity-Technologies/com.autodesk.fbx/pull/414).
This PR is to add an ARM64 Win build job for CI of `com.unity.formats.fbx` when it uses submodule `com.autodesk.fbx`.
[FBX-517](https://jira.unity3d.com/browse/FBX-517) Create Yamato job to build library on Win ARM64

Add build job on Win Arm64 for autodesk.fbx submodule 

---

.yamato/global.metafile

Remove 2023.1 from CI of release/5.0 branch.
[FBX-494](https://jira.unity3d.com/browse/FBX-494) CI: Editor cleanup in CI of both FBX SDK and FBX Exporter for release/5.0 branch

Remove 2023.1 from CI for release/5.0 branch

---

com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs

Disable AnimOnlyExportTest for release 4.2
[FBX-536](https://jira.unity3d.com/browse/FBX-536) CI: Disable test FbxAnimationTest.AnimOnlyExportTest for release/4.2 and release/5.0 branch

Disable AnimOnlyExportTest for release 4.2

---

com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs

CI: Disable AnimOnlyExportTest for release/5.0 branch
[FBX-536](https://jira.unity3d.com/browse/FBX-536)
CI: Disable test FbxAnimationTest.AnimOnlyExportTest for release/4.2 and release/5.0 branch

CI: Disable AnimOnlyExportTest for release/5.0 branch

---

.yamato/global.metafile

Remove 2023.2 from main branch CI
[FBX-535](https://jira.unity3d.com/browse/FBX-535) CI: Remove 2023.2 from FBX Exporter's Editor list

Remove 2023.2 from main branch CI

---

CHANGELOG.md
com.unity.formats.fbx/Editor/FbxExporter.cs
com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs
com.unity.formats.fbx/package.json

Jira issue: https://jira.unity3d.com/browse/FBX-344
It was raised by Viktoria a while ago. Not sure how she bumped into it but after a quick search, it is indeed possible to have an LOD with a null renderer. Cf issue for more details.
Note I also upgraded the version of the package because it seems it is the workflow APV 2.0 wants us to have (aka as soon as you add an Unreleased section, version should be updated).

Fixed exception when exporting with an LOD containing a null renderer (FBX-344)

---

com.unity.formats.fbx/Documentation~/api_index.md
com.unity.formats.fbx/Documentation~/export.md
com.unity.formats.fbx/Documentation~/features-behaviors.md
com.unity.formats.fbx/Documentation~/index.md
com.unity.formats.fbx/Documentation~/prefab-variants.md
com.unity.formats.fbx/Editor/ConvertToNestedPrefab.cs
com.unity.formats.fbx/Editor/FbxExporter.cs

Clean up the landing page of the FBX Exporter package Scripting API documentation.
- [DOCATT-5036](https://jira.unity3d.com/browse/DOCATT-5036) - Rewrite Developer's Guide to match landing page standards
- [DOCATT-5034](https://jira.unity3d.com/browse/DOCATT-5034) - Move Runtime section
- [DOCATT-5031](https://jira.unity3d.com/browse/DOCATT-5031) - Find better places for use cases
**Note:** in KTLO context, we don't push too much for moving things around. The three tickets listed above actually converged to a straightforward cleanup of the targeted page.
In the end:
- Adjusted the page title and added a short intro sentence.
- Grouped/identified all topics in a Get started section with subsections.
- Presented topics from use case to main corresponding class and provided links to these …

Clean up API doc landing page

---

.yamato/upm-ci.yml

- Remove `PVP-41-1` check from `upm-pvp` commands in pack job
- Add `upm-pvp` commands with `PVP-41-1` check in `publish dry-run` job so that "Unreleased" section in Changelog won't slip through the crack when being released.
[FBX-540](https://jira.unity3d.com/browse/FBX-540) CI: Add upm-pvp commands to "publish dry-run" job

CI: Add upm-pvp commands with PVP-41-1 check to publish dry-run job

---

CHANGELOG.md
com.unity.formats.fbx/Editor/ExportModelEditorWindow.cs
com.unity.formats.fbx/Editor/FbxExportPresetSelectorReceiver.cs

`PresetSelectorReceiver` was deprecated in 2023.1 and presets were actually not working anymore in 2023 stream.
Replaced PresetSelectorReceiver by the new API for 2023.1+.
Removed the pragmas to prevent warnings.
Tested in 6000 and 2022.3:
* Presets are working
* There is no warning

Remove usage of deprecated PresetSelectorReceiver (FBX-452)

---

.yamato/package-format.yml

Use YAMATO_OWNER_EMAIL environment variable instead of [noreply@unity3d.com](mailto:noreply@unity3d.com) in format_code job.
By doing that, whoever runs that job will be the author of that commit which formats the codes.
[CST-1470](https://jira.unity3d.com/browse/CST-1470) CI: Use YAMATO_OWNER_EMAIL in format_code jobs

CI: Use YAMATO_OWNER_EMAIL environment variable in package format job

---

com.unity.formats.fbx/Documentation~/includes/transfer-animation.md
com.unity.formats.fbx/Documentation~/ref-convert-options.md
com.unity.formats.fbx/Documentation~/ref-export-options.md
com.unity.formats.fbx/Documentation~/ref-recorder-properties.md

Fix missing/incomplete property references according to various feedback sources:

Doc - Fix missing/incomplete property references
