Unity-Technologies/com.unity.formats.fbx

com.unity.formats.fbx/Editor/FbxExporter.cs
We just verify a null inside IsEditorClip.
=> Added the required small fix

Integrations/Autodesk/maya/scripts/unityCommands.mel, Integrations/Autodesk/maya/scripts/unitySetupUI.mel.in
=> Ut 3356 add create export set option

.yamato/promotion.yml, .yamato/upm-ci.yml
https://unity.slack.com/archives/C26EP4SUQ/p1587408311155000
=> UT-3387 update registry as bintray will no longer be used

.yamato/upm-ci.yml
I guess this will need to happen on the other projects as well.
=> Update image for mac for compatibility with upm-ci 1.9.0

com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs
Fixed an error in the tests where the importer wasn't being reassigned.
=> UT-1945 Tests Fix

CHANGELOG.md, com.unity.formats.fbx/Editor/ExportModelSettings.cs, com.unity.formats.fbx/Tests/FbxTests/FbxExportSettingsTest.cs
Note: constraint tests failing due to axis conversion changes
=> Ut 3710 fix export settings presets not working

com.unity.formats.fbx/Tests/FbxTests/FbxConstraintTest.cs
- There are currently known issues with constraint import
=> UT-3195 ignore failing constraint tests

com.unity.formats.fbx/Tests/FbxTests/FbxConstraintTest.cs, com.unity.formats.fbx/Tests/FbxTests/ModelExporterTest.cs
+ remove unused function in constraint test
=> FBX-45 add negative scale unit test

com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs
Adding tests for FBXAnimationTest.cs. 
Adding blendshape animations to the existing blenshape.fbx test model and checking keyframes values before and after export using AnimTester.
=> FBX 71: Blendshape Animation Tests

com.unity.formats.fbx/Editor/FbxExporter.cs, com.unity.formats.fbx/Editor/IExportData.cs, com.unity.formats.fbx/Tests/FbxTests/FbxAnimationTest.cs
make sure to export the mesh and blendshapes in animation only export mode.
=> FBX-134 export skinned mesh if exporting blendshape animation

.yamato/promotion.yml, .yamato/upm-ci.yml, com.unity.formats.fbx/Tests/.tests.json
Note: failing from timeline missing dependencies
=> add isolation test flag

CHANGELOG.md, com.unity.formats.fbx/Editor/FbxExporter.cs
Bug fix for nullReferenceException when animation motion is missing.
=> FBX-55 Fix Null Animation

CHANGELOG.md, com.unity.formats.fbx/Editor/ConvertToNestedPrefab.cs, com.unity.formats.fbx/Editor/FbxExporter.cs, com.unity.formats.fbx/Tests/FbxTests/ConvertToModelTest.cs
Fix prefab staying renamed after undoing prefab creation
=> FBX 92 Fix prefab rename on undo

.yamato/upm-ci.yml
Adds validate_* steps on publish. These run the Package Validation Suite (PVS).
=> added validation step for publish CI

.yamato/upm-ci.yml
Enabling package signing during publish.
Learn more at https://confluence.unity3d.com/display/PAK/Package+Signature
#team-pkd-176-internal-package-signing
@cassandra (etherElric) & @felipemunoz
=> Package SIgnature in CI

.yamato/upm-ci.yml, CHANGELOG.md
Fixing the CI (currently all the job are failing because of the missing changelog entry) and updating the editor versions.
Also added some nighly builds and adding back Ubuntu plateform.
=> CI: updates for Sapphire (FBX-282)

.yamato/upm-ci.yml
2022.2 did not have the test cases generated for it
=> fix nightlies not running on master and release/4.2

com.unity.formats.fbx/package.json
updating the package version so the validation test doesn't fail because the major version didn't change after making api changes
=> update package version

.buginfo
To help Engineering Services to create Jira tickets in the right project, they asked us to create a .buginfo files that does the link between pieces of code and JIRA projects.
Full instruction can be found on Slack here: https://unity.slack.com/archives/C06TQ0QMQ/p1654162527039159
When we validate and merge this PR, don't forget to mark the package as Done in [this spreadsheet](https://docs.google.com/spreadsheets/d/1Oar8xCBSmuy8Q7LWusdDZm6XZXSCnChkz4iLs8rMiKs/edit#gid=645248065).
=> Repo: add .buginfo file (FBX-342)

CHANGELOG.md, com.unity.formats.fbx/package.json
Note: tests will fail until bindings package is published
=> FBX-388 update to version 4.1.3

.yamato/upm-ci.yml
Remove trunk from other places for 4.2 branch
=> Remove trunk from other triggers for 4.2 branch

com.unity.formats.fbx/Documentation~/index.md
Documentation update: requirements section
- [FBX-381](https://jira.unity3d.com/browse/FBX-381) - Update supported Unity Editor and Maya/Max versions
Note: This update is for FBX Exporter 5.0.0
=> Update requirements in user manual

com.unity.formats.fbx/Documentation~/index.md
Backport from [PR#683](https://github.com/Unity-Technologies/com.unity.formats.fbx/pull/683) - Documentation update: requirements section
- [FBX-381](https://jira.unity3d.com/browse/FBX-381) - Update supported Unity Editor and Maya/Max versions
=> Doc backport - Update requirements in user manual

.yamato/global.metafile
Add 2023.1 to master branch's CI
[FBX-458](https://jira.unity3d.com/browse/FBX-458) CI: Add 2023.1 and trunk to FBX CI
=> FBX-458 Add 2023.1 to master branch's CI

com.unity.formats.fbx/Documentation~/exporting.md
Just mentioning this new one.
Should I mention somewhere we use depth of field property ?
=> Update doc for 5.1.0 (FBX-474)

.yamato/upm-ci.yml
=> Rename main branch to main (FBX-537)

.yamato/global.metafile, .yamato/package-test-utr.yml, .yamato/upm-ci.yml
[CST-1482](https://jira.unity3d.com/browse/CST-1482) CI: Add 6000.0 to cinematic pipeline packages' CI
=> Add 6000.0 to CI

CHANGELOG.md
=> Prepare changelog for release (FBX-539)

CHANGELOG.md, com.unity.formats.fbx/Editor/ExportSettings.cs, com.unity.formats.fbx/package.json
**Ticket/Jira #:** (fbx-545)
An indent was unintentionally removed in project setting and was preventing straightforward toggling of checkboxes (you had to click next to the checkbox).
Manual testing
| User interface | N  |  |
| Public API docs | N |   |
| Changelog | Y |  |
| User manual | N |  |
| Other docs | N |  |
**Reminder:**
=> Fix settings indent (fbx-545)

.yamato/global.metafile
6000.1 has been branched off from trunk which has become 6000.2 now. Because of this, I need to add 6000.1 to CI of our packages.
[FBX-547](https://jira.unity3d.com/browse/FBX-547) CI: Add 6000.1 to CI
**Reminder:**
=> Add 6000.1 to CI

.yamato/global.metafile
Update Ubuntu image to 22.04 because 20.04 is not supported by Trunk any more.
**Reminder:**
=> CI: Update Ubuntu image to 22.04

CHANGELOG.md, com.unity.formats.fbx/Editor/ConvertToNestedPrefab.cs, com.unity.formats.fbx/Editor/FbxExporter.cs, com.unity.formats.fbx/Tests/FbxTests/FbxExportSettingsTest.cs, com.unity.formats.fbx/package.json
**Ticket/Jira #:** https://jira.unity3d.com/browse/FBX-558
**Reminder:**
=> Upgrading InstanceId to EntityId (FBX-558)

CHANGELOG.md
Update changelog for 5.1.4
**Reminder:**
=> Update changelog for 5.1.4
